// src/components/Table.tsx
import { DataTable, DataTableExpandedRows } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { Button } from 'primereact/button';
import { Paginator } from 'primereact/paginator';
import { useMemo, useState } from 'react';

export type ColumnSettings = {
  field: string;
  header: string;
  showFilter?: boolean;
  transform?: (value: any) => any;
  className?: string;
  collapsibleRow?: boolean;
  width?: string;
  minWidth?: string;
  maxWidth?: string;
};

export type ActionSettings = {
  title: string;
  showTitle?: boolean;
  icon?: string;
  func: (row: any, ...params: any[]) => void;
  class?: string[];
  params: any[];
  size?: 'small' | 'large';
  outlined?: boolean;
  severity?:
    | 'success'
    | 'info'
    | 'warning'
    | 'danger'
    | 'help'
    | 'primary'
    | 'secondary'
    | 'contrast';
  showWhen?: (data: any) => boolean;
};

export type TableSettings = {
  columns: ColumnSettings[];
  actions?: ActionSettings[];
  selectable?: boolean;
  expandable?: boolean;
  expandableHeader?: boolean;
  childTableSettings?: TableSettings;
};

export type PageEvent = { first: number; page: number; pageCount: number; rows: number };

export function Table(props: {
  settings: TableSettings;
  records: any[];
  loading?: boolean;
  selectedRecords?: any[];
  emptyMessage?: string;
  totalRecords: number;
  totalPages?: number;
  paginate?: boolean;
  pageSize?: number;
  rowsPerPage?: number[];
  enableSort?: boolean;
  enableFilter?: boolean;
  enableGlobalFilter?: boolean;
  enableShowDeactivatedToggle?: boolean;
  onPageChange?: (event: PageEvent) => void;
}) {
  const {
    settings,
    records,
    loading = false,
    emptyMessage = 'No records found',
    totalRecords,
    paginate = true,
    pageSize = 10,
    rowsPerPage = [10, 20, 50],
    enableSort = true,
    onPageChange
  } = props;

  const [first, setFirst] = useState(0);
  const [rows, setRows] = useState(pageSize);
  const [expandedRows, setExpandedRows] = useState<DataTableExpandedRows | any[]>([]);

  const columns = useMemo(() => settings.columns, [settings.columns]);

  const actionsHeader = settings.actions ? (
    <Column key="__actions_header" header="Action" body={(row) => (
      <div className="flex gap-2 justify-content-center">
        {settings.actions?.map((action) =>
          (!action.showWhen || action.showWhen(row)) ? (
            <Button
              key={action.title}
              icon={action.icon}
              label={action.showTitle ? action.title : undefined}
              size={action.size as any}
              severity={action.severity as any}
              outlined={action.outlined}
              onClick={() => action.func(row, ...(action.params || []))}
            />
          ) : null
        )}
      </div>
    )} style={{ width: 150 }} />
  ) : null;

  const onPaginate = (e: any) => {
    setFirst(e.first ?? 0);
    setRows(e.rows ?? pageSize);
    onPageChange?.({ first: e.first ?? 0, rows: e.rows ?? pageSize, page: e.page ?? 0, pageCount: e.pageCount ?? 0 });
  };

  const rowExpansionTemplate = (row: any) => {
    if (!settings.childTableSettings || !(row?.children?.length > 0)) return null;
    return (
      <div className="p-3">
        <Table
          settings={settings.childTableSettings}
          records={row.children}
          totalRecords={row.children.length}
          paginate={false}
          enableSort={false}
        />
      </div>
    );
  };

  return (
    <div>
      <div className="flex mt-3 justify-content-between px-0">
        <div className="flex gap-2">
          {settings.actions?.map((action) => (
            <Button key={action.title} label={action.title} icon={action.icon} severity={action.severity as any} onClick={() => action.func({}, ...(action.params || []))} />
          ))}
        </div>
      </div>

      <DataTable
        value={records}
        loading={loading}
        paginator={false}
        first={first}
        rows={rows}
        tableStyle={{ minWidth: '50rem' }}
        expandedRows={expandedRows}
        onRowToggle={(e) => setExpandedRows(e.data)}
        rowExpansionTemplate={rowExpansionTemplate}
      >
        {settings.expandable && <Column expander style={{ width: '4rem' }} />}
        {settings.selectable && <Column selectionMode="multiple" style={{ width: '4rem' }} />}
        {columns.map((col) => (
          <Column
            key={col.field}
            field={col.field}
            header={col.header}
            sortable={enableSort}
            style={{ width: col.width, minWidth: col.minWidth, maxWidth: col.maxWidth }}
          />
        ))}
        {actionsHeader}
      </DataTable>

      {paginate && (
        <Paginator
          first={first}
          rows={rows}
          totalRecords={totalRecords}
          rowsPerPageOptions={rowsPerPage}
          onPageChange={(e) => onPaginate(e as any)}
        />
      )}

      {!records?.length && !loading && (
        <div className="text-center p-3">{emptyMessage}</div>
      )}
    </div>
  );
}

// src/app/shared/components/table/table.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { ColumnSettings, PageEvent, TableSettings, ExpandableTableData } from '../../models/table.interface';
import { ActionSettings } from '../../models/action.interface';
import { Subject, debounceTime, distinctUntilChanged } from 'rxjs';
@Component({
  selector: 'portfolio-editor-table',
  templateUrl: './table.component.html',
  styleUrl: './table.component.scss',
  providers: [],
})

export class TableComponent {
  @Input() settings!: TableSettings;
  @Input() records!: any[];
  @Input() loading: boolean = false;
  @Input() selectedRecords: any[] = [];
  @Input() emptyMessage = 'No records found';
  @Input() actions: ActionSettings[] | undefined;

  // Filtering
  @Input() enableSort: boolean = false;
  @Input() enableFilter: boolean = false;
  @Input() enableGlobalFilter: boolean = false;
  @Input() enableShowDeactivatedToggle: boolean = false;
  @Input() enableServerSideFilter: boolean = false;

  // Pagination
  @Input() totalRecords!: number;
  @Input() totalPages!: number;
  @Input() paginate: boolean = false;
  @Input() pageSize: number = 10;
  @Input() rowsPerPage: number[] = [10, 20, 50];

  // Events
  @Output() selectionChange = new EventEmitter<any[]>();
  @Output() pageChange = new EventEmitter<PageEvent>();
  @Output() showDeactivatedChange = new EventEmitter<boolean>();
  @Output() searchChange = new EventEmitter<string>();
  @Output() rowExpand = new EventEmitter<any>();
  @Output() rowCollapse = new EventEmitter<any>();

  columnMaps!: ColumnSettings[];
  globalFilters: string[] = [];
  showDeactivated: boolean = false;
  showActionButton: boolean = false;

  private searchSubject = new Subject<string>();

  constructor() {
    this.searchSubject.pipe(
      debounceTime(800),
      distinctUntilChanged()
    ).subscribe((term) => {
      this.searchChange.emit(term);
    });
  }

  ngOnInit() {
    this.columnMaps = this.settings.columns;
    this.globalFilters = this.columnMaps.map((c) => c.field);
    this.records = this.records?.map(record => ({
      ...record,
      collapsed: true, // Default to collapsed
      expanded: false // For accordion functionality
    }));
  }

  actionClick(record: object, func: any, params: any) {
    func(record, ...params);
  }

  onSelectionChange(event: any) {
    this.selectionChange.emit(this.selectedRecords);
  }

  get currentPageReportTemplate() {
    return `Showing {first} to {last} of ${this.totalRecords} entries`;
  }

  onPageChange(event: any) {
    this.pageChange.emit(event as PageEvent);
  }

  toggleCollapse(rowData: any) {
    rowData.collapsed = !rowData.collapsed;
  }

  // New method for accordion functionality
  toggleExpand(rowData: ExpandableTableData) {
    rowData.expanded = !rowData.expanded;
    if (rowData.expanded) {
      this.rowExpand.emit(rowData);
    } else {
      this.rowCollapse.emit(rowData);
    }
  }

  // Check if row has children
  hasChildren(rowData: any): boolean {
    return this.settings.expandable && rowData.children && rowData.children.length > 0;
  }

  onShowDeactivatedChange() {
    this.showDeactivatedChange.emit(this.showDeactivated);
  }

  onShowActionButton(record: any, showWhen: any) {
    return showWhen instanceof Function ? showWhen(record) : showWhen;
  }

  triggerSearch(term: string) {
    this.searchChange.emit(term);
  }
}

<p-table
  #dt1
  dataKey="id"
  class="p-fluid"
  [tableStyle]="{ 'min-width': '50rem' }"
  [columns]="columnMaps"
  [value]="records"
  [rows]="pageSize"
  [rowsPerPageOptions]="rowsPerPage"
  [showCurrentPageReport]="true"
  [currentPageReportTemplate]="currentPageReportTemplate"
  [globalFilterFields]="globalFilters"
  [selectionMode]="settings.selectable ? 'multiple' : null"
  [(selection)]="selectedRecords"
  (selectionChange)="onSelectionChange($event)"
  (onPage)="onPageChange($event)"
  [totalRecords]="totalRecords"
>
  <ng-template pTemplate="caption">
    <div class="flex mt-3 justify-content-between px-0">
      <div class="flex">
        <p-button
          *ngFor="let action of actions"
          label="{{ action.title }}"
          icon="{{ action.icon }}"
          [severity]="action.severity"
          (onClick)="actionClick({}, action.func, action.params)"
        ></p-button>
      </div>
      <div class="flex flex-column align-items-center">
        <div *ngIf="enableGlobalFilter">
          <p-iconField iconPosition="left" class="ml-auto">
            <p-inputIcon>
              <i class="pi pi-search"></i>
            </p-inputIcon>
            <input
              *ngIf="enableServerSideFilter"
              pInputText
              type="text"
              placeholder="Search keyword"
              (input)="triggerSearch($any($event).target.value)"
            />
            <input
              *ngIf="!enableServerSideFilter"
              pInputText
              type="text"
              (input)="dt1.filterGlobal($any($event).target.value, 'contains')"
              placeholder="Search keyword"
            />
          </p-iconField>
        </div>
        <div *ngIf="enableShowDeactivatedToggle" class="mt-3">
          <p-checkbox
            inputId="ny"
            [(ngModel)]="showDeactivated"
            (ngModelChange)="onShowDeactivatedChange()"
            [binary]="true"
          />
          <label for="ny" class="ml-2 cursor-pointer">Show Deactivated</label>
        </div>
      </div>
    </div>
  </ng-template>
  <ng-template pTemplate="header" let-columns>
    <tr>
      <!-- Expand/Collapse column for accordion -->
      <th *ngIf="settings.expandable" style="width: 4rem">
        <i *ngIf="settings.expandableHeader" class="pi pi-chevron-right"></i>
      </th>
      <th *ngIf="settings.selectable" style="width: 4rem">
        <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
      </th>
      <th
        *ngFor="let col of columns"
        [pSortableColumn]="enableSort ? col.field : null"
        [ngClass]="col.className"
        [style.width]="col.width || 'auto'"
        [style.min-width]="col.minWidth || 'auto'"
        [style.max-width]="col.maxWidth || 'auto'"
      >
        {{ col.header }}
        <p-sortIcon *ngIf="enableSort" field="{{ col.field }}" />
        <p-columnFilter
          type="text"
          field="{{ col.field }}"
          ariaLabel="Filter {{ col.header }}"
          display="menu"
          *ngIf="col.showFilter"
        />
      </th>
      <!-- Fixed action header -->
      <th *ngIf="settings.actions" class="actions-column-header">
        <div class="actions-header-content">Action</div>
      </th>
    </tr>
  </ng-template>
  <ng-template pTemplate="body" let-rowData let-columns="columns" let-rowIndex="rowIndex">
    <!-- Parent Row -->
    <tr [pSelectableRow]="rowData" [ngClass]="{'expandable-row': settings.expandable}">
      <!-- Expand/Collapse toggle -->
      <td *ngIf="settings.expandable" style="width: 4rem; text-align: left;">
        <button
          *ngIf="hasChildren(rowData)"
          type="button"
          pButton
          class="p-button-text p-button-sm accordion-toggle"
          [icon]="rowData.expanded ? 'pi pi-minus' : 'pi pi-plus'"
          (click)="toggleExpand(rowData)"
        ></button>
      </td>

      <td *ngIf="settings.selectable">
        <p-tableCheckbox
          [pSelectableRow]="rowData"
          [value]="rowData"
        ></p-tableCheckbox>
      </td>

      <ng-container *ngFor="let col of columns">
        <td [style.width]="col.width || 'auto'" [style.min-width]="col.minWidth || 'auto'">
          <p-skeleton *ngIf="loading" />
          <div *ngIf="records && !loading">
            <!-- display for simple string value -->
            <div *ngIf="!col.collapsibleRow">
              {{
                col.transform
                  ? col.transform(rowData[col.field])
                  : rowData[col.field]
              }}
            </div>
            <!-- collapsible display for multiple line value like json format value -->
            <button
              type="button"
              class="collapse-btn"
              pButton
              icon="pi pi-angle-right"
              (click)="toggleCollapse(rowData)"
              *ngIf="
                col.collapsibleRow &&
                !rowData.collapsed &&
                (col.transform
                  ? col.transform(rowData[col.field])
                  : rowData[col.field]) != null
              "
            ></button>
            <div
              class="value-container"
              (click)="toggleCollapse(rowData)"
              *ngIf="col.collapsibleRow && rowData.collapsed"
            >
              {{
                col.transform
                  ? col.transform(rowData[col.field])
                  : rowData[col.field]
              }}
            </div>
          </div>
        </td>
      </ng-container>

      <!-- Fixed action field -->
      <td *ngIf="settings.actions" class="actions-column-cell">
        <div class="actions-cell-content">
          <p-buttonGroup>
            <ng-container *ngFor="let action of settings.actions">
              <p-button
                *ngIf="!action.showWhen || action.showWhen(rowData)"
                icon="{{ action.icon }}"
                [label]="action.showTitle ? action.title : undefined"
                [size]="action.size"
                [severity]="action.severity"
                [outlined]="action.outlined"
                (onClick)="actionClick(rowData, action.func, action.params)"
                pTooltip="{{ action.title }}"
                tooltipPosition="left"
              >
              </p-button>
            </ng-container>
          </p-buttonGroup>
        </div>
      </td>
    </tr>

    <!-- Child Table Row (Expanded Content) -->
    <tr *ngIf="settings.expandable && rowData.expanded && hasChildren(rowData)" class="child-table-row">
      <td [attr.colspan]="(settings.expandable ? 1 : 0) + (settings.selectable ? 1 : 0) + columnMaps.length + (settings.actions ? 1 : 0)">
        <div class="child-table-container">
          <!-- Render child table -->
          <portfolio-editor-table
            *ngIf="settings.childTableSettings"
            [settings]="settings.childTableSettings"
            [records]="rowData.children"
            [loading]="false"
            [enableSort]="false"
            [enableFilter]="false"
            [enableGlobalFilter]="false"
            [enableShowDeactivatedToggle]="false"
            [paginate]="false"
            [emptyMessage]="'No child records found'"
          ></portfolio-editor-table>

          <!-- Alternative: Simple child data display if no child table settings -->
          <div *ngIf="!settings.childTableSettings" class="simple-child-display">
            <div *ngFor="let child of rowData.children" class="child-item p-2 border-bottom-1">
              {{ child | json }}
            </div>
          </div>
        </div>
      </td>
    </tr>
  </ng-template>
  <ng-template pTemplate="emptymessage">
    <tr>
      <td colspan="100%" class="text-center">{{ emptyMessage }}</td>
    </tr>
  </ng-template>
</p-table>

<p-paginator
  (onPageChange)="onPageChange($event)"
  [first]="0"
  [rows]="pageSize"
  [totalRecords]="totalRecords"
  [rowsPerPageOptions]="rowsPerPage"
/>
