// src/app/portfolio-mgmt/component/portfolio-management/portfolio-management.component.ts
import { Component } from '@angular/core';
import { TableSettings } from '../../../shared/models/table.interface';
import { ActionSettings, Mode } from '../../../shared/models/action.interface';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-portfolio-management',
  templateUrl: './portfolio-management.component.html',
  styleUrl: './portfolio-management.component.scss',
})
export class PortfolioManagementComponent {
  //MOCK DATA
  // Updated table data with proper field names
  tableData = [
    {
      planCode: 'PC001',
      orgnaization: 'Org A',
      cocSeries: 'COC-A',
      state: 'CA',
      segment: 'KA',
      license: 'LIC001',
      product: 'Product-A',
      standard: 'Standard',
    },
    {
      planCode: 'PC002',
      orgnaization: 'Org A',
      cocSeries: 'COC-B',
      state: 'TX',
      segment: 'KA',
      license: 'LIC002',
      product: 'Product-A',
      standard: 'Standard',
    },
    {
      planCode: 'PC003',
      orgnaization: 'Org A',
      cocSeries: 'COC-C',
      state: 'NY',
      segment: 'KA',
      license: 'LIC003',
      product: 'Product-A',
      standard: 'Standard',
    },
  ];

  // Dropdown options
  segmentOptions = [
    { label: 'KA', value: 'KA' },
    { label: 'KB', value: 'KB' },
    { label: 'KC', value: 'KC' },
  ];

  stateOptions = [
    { label: 'California', value: 'CA' },
    { label: 'Texas', value: 'TX' },
    { label: 'New York', value: 'NY' },
    { label: 'Florida', value: 'FL' },
  ];

  cocSeriesOptions = [
    { label: 'COC-A', value: 'COC-A' },
    { label: 'COC-B', value: 'COC-B' },
    { label: 'COC-C', value: 'COC-C' },
  ];

  licenseOptions = [
    { label: 'LIC001', value: 'LIC001' },
    { label: 'LIC002', value: 'LIC002' },
    { label: 'LIC003', value: 'LIC003' },
  ];

  productOptions = [
    { label: 'Product-A', value: 'Product-A' },
    { label: 'Product-B', value: 'Product-B' },
    { label: 'Product-C', value: 'Product-C' },
  ];

  standardOptions = [
    { label: 'Standard', value: 'Standard' },
    { label: 'Custom', value: 'Custom' },
  ];

  planTypeOptions = [
    { label: 'Type-A', value: 'Type-A' },
    { label: 'Type-B', value: 'Type-B' },
    { label: 'Type-C', value: 'Type-C' },
  ];

  searchForm: FormGroup;
  // Table state
  loading = false;
  totalRecords = this.tableData.length;
  totalPages = 1;
  // Table actions
  tableActions: ActionSettings[] = [
    {
      title: Mode.Standard,
      showTitle: true,
      func: this.createStandard.bind(this),
      params: [],
      size: 'small',
      outlined: true,
      severity: 'primary',
      showWhen: () => true,
    },
    {
      title: Mode.Custom,
      showTitle: true,
      func: this.createCustom.bind(this),
      params: [],
      size: 'small',
      outlined: true,
      severity: 'primary',
      showWhen: () => true,
    },
  ];
  // Table configuration
  tableSettings: TableSettings = {
    columns: [
      {
        field: 'planCode',
        header: 'Plan Code',
        width: '120px',
        minWidth: '100px'
      },
      {
        field: 'cocSeries',
        header: 'COC Series',
        width: '140px',
        minWidth: '120px'
      },
      {
        field: 'state',
        header: 'State',
        width: '100px',
        minWidth: '80px'
      },
      {
        field: 'segment',
        header: 'Segment',
        width: '100px',
        minWidth: '80px'
      },
      {
        field: 'license',
        header: 'License',
        width: '120px',
        minWidth: '100px'
      },
      {
        field: 'product',
        header: 'Published',
        width: '140px',
        minWidth: '120px'
      },
      {
        field: 'standard',
        header: 'Standard',
        width: '120px',
        minWidth: '100px'
      },
    ],
    actions: this.tableActions,
    selectable: false,
  };

  constructor(private fb: FormBuilder, private router: Router, private route: ActivatedRoute) {
    this.searchForm = this.fb.group({
      planCode: [''],
      segment: [''],
      state: [''],
      cocSeries: [''],
      license: [''],
      product: [''],
      standard: [''],
      planType: [''],
    });
  }

  // Event handlers

  // Form event handlers
  onSearch() {
    const formValues = this.searchForm.value;
    console.log('Search form values:', formValues);
    // Implement search functionality
  }

  onClear() {
    this.searchForm.reset();
    console.log('Form cleared');
  }

  onPageChange(event: any) {
    console.log('Page changed:', event);
    // Handle pagination if needed
  }

  // Action handlers
  createStandard(record: any) {
    console.log('Edit record:', record);
    this.router.navigate(['/portfolio-management/portfolio-editor']);
    // Implement edit functionality
  }

  createCustom(record: any) {
    console.log('View record:', record);
    this.router.navigate(['/portfolio-management/portfolio-editor']);
    // Implement view functionality
  }
}

<div>
  <p-tabView>
    <p-tabPanel header="Portfolio Management" [selected]="true">
      <h1>Portfolio Management</h1>
      <div class="p-card p-3 m-5">

        <div class="p-card-body">
          <form [formGroup]="searchForm" (ngSubmit)="onSearch()">
            <div class="grid">
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <input id="planCode" type="text" pInputText formControlName="planCode" class="w-full" />
                  <label for="planCode">Plan Code</label>
                </div>
              </div>
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <p-dropdown id="segment" formControlName="segment" [options]="segmentOptions" optionLabel="label"
                    optionValue="value" [placeholder]="' '" class="w-full"
                    [ngClass]="{'has-value': searchForm.get('segment')?.value}">
                  </p-dropdown>
                  <label for="segment" [ngClass]="{'label-float': searchForm.get('segment')?.value}">Segment</label>
                </div>
              </div>
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <p-dropdown id="state" formControlName="state" [options]="stateOptions" optionLabel="label"
                    optionValue="value" [placeholder]="' '" class="w-full"
                    [ngClass]="{'has-value': searchForm.get('state')?.value}">
                  </p-dropdown>
                  <label for="state" [ngClass]="{'label-float': searchForm.get('state')?.value}">State</label>
                </div>
              </div>
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <p-dropdown id="cocSeries" formControlName="cocSeries" [options]="cocSeriesOptions"
                    optionLabel="label" optionValue="value" [placeholder]="' '" class="w-full"
                    [ngClass]="{'has-value': searchForm.get('cocSeries')?.value}">
                  </p-dropdown>
                  <label for="cocSeries" [ngClass]="{'label-float': searchForm.get('cocSeries')?.value}">COC
                    Series</label>
                </div>
              </div>
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <p-dropdown id="license" formControlName="license" [options]="licenseOptions" optionLabel="label"
                    optionValue="value" placeholder="Select License" class="w-full">
                  </p-dropdown>
                  <label for="license">License</label>
                </div>
              </div>
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <p-dropdown id="product" formControlName="product" [options]="productOptions" optionLabel="label"
                    optionValue="value" placeholder="Select Product" class="w-full">
                  </p-dropdown>
                  <label for="product">Product</label>
                </div>
              </div>
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <p-dropdown id="standard" formControlName="standard" [options]="standardOptions" optionLabel="label"
                    optionValue="value" placeholder="Select Standard" class="w-full">
                  </p-dropdown>
                  <label for="standard">Standard</label>
                </div>
              </div>
              <div class="flex justify-content-center col-3 p-2 mt-2">
                <div class="p-float-label w-full">
                  <p-dropdown id="planType" formControlName="planType" [options]="planTypeOptions" optionLabel="label"
                    optionValue="value" placeholder="Select Plan Type" class="w-full">
                  </p-dropdown>
                  <label for="planType">Plan Type</label>
                </div>
              </div>
            </div>

            <div class="flex">
              <button type="button" pButton label="Clear" size="small" [outlined]="true" severity="warning"
                class="flex-1 flex align-items-center justify-content-center m-2" (click)="onClear()">
              </button>
              <button type="submit" pButton label="Search" size="small" [outlined]="true"
                class="flex-1 flex align-items-center justify-content-center m-2">
              </button>
            </div>
          </form>

          <div class="p-3">
            <portfolio-editor-table [settings]="tableSettings" [records]="tableData" [loading]="loading"
              [totalRecords]="totalRecords" [totalPages]="totalPages" [paginate]="true" [enableSort]="true"
              [enableFilter]="true" [enableShowDeactivatedToggle]="false" [pageSize]="25" [rowsPerPage]="[10, 25, 50]"
              (pageChange)="onPageChange($event)">
            </portfolio-editor-table>
          </div>
        </div>

        <p-toast [life]="5000" position="bottom-right"></p-toast>
      </div>
    </p-tabPanel>
    <p-tabPanel header="My Plans">
      <h1>My Plans</h1>
      <div class="p-card p-3 m-5">
        <app-my-plans></app-my-plans>
      </div>
    </p-tabPanel>
  </p-tabView>
</div>

// src/pages/PortfolioManagement.tsx
import { useMemo, useState } from 'react';
import { Button } from 'primereact/button';
import { Dropdown } from 'primereact/dropdown';
import { InputText } from 'primereact/inputtext';
import { TabView, TabPanel } from 'primereact/tabview';
import { Table, TableSettings, ActionSettings } from '@/components/Table';
import { useNavigate } from 'react-router-dom';

export function PortfolioManagement() {
  const navigate = useNavigate();
  const [search, setSearch] = useState({
    planCode: '',
    segment: '',
    state: '',
    cocSeries: '',
    license: '',
    product: '',
    standard: '',
    planType: ''
  });

  const tableData = useMemo(() => ([
    { planCode: 'PC001', orgnaization: 'Org A', cocSeries: 'COC-A', state: 'CA', segment: 'KA', license: 'LIC001', product: 'Product-A', standard: 'Standard' },
    { planCode: 'PC002', orgnaization: 'Org A', cocSeries: 'COC-B', state: 'TX', segment: 'KA', license: 'LIC002', product: 'Product-A', standard: 'Standard' },
    { planCode: 'PC003', orgnaization: 'Org A', cocSeries: 'COC-C', state: 'NY', segment: 'KA', license: 'LIC003', product: 'Product-A', standard: 'Standard' }
  ]), []);

  const actions: ActionSettings[] = [
    { title: 'Standard', showTitle: true, func: () => navigate('/portfolio-management/portfolio-editor'), params: [], size: 'small', outlined: true, severity: 'primary' },
    { title: 'Custom', showTitle: true, func: () => navigate('/portfolio-management/portfolio-editor'), params: [], size: 'small', outlined: true, severity: 'primary' }
  ];

  const tableSettings: TableSettings = {
    columns: [
      { field: 'planCode', header: 'Plan Code', width: '120px', minWidth: '100px' },
      { field: 'cocSeries', header: 'COC Series', width: '140px', minWidth: '120px' },
      { field: 'state', header: 'State', width: '100px', minWidth: '80px' },
      { field: 'segment', header: 'Segment', width: '100px', minWidth: '80px' },
      { field: 'license', header: 'License', width: '120px', minWidth: '100px' },
      { field: 'product', header: 'Published', width: '140px', minWidth: '120px' },
      { field: 'standard', header: 'Standard', width: '120px', minWidth: '100px' }
    ],
    actions,
    selectable: false
  };

  return (
    <TabView>
      <TabPanel header="Portfolio Management" leftIcon="pi pi-briefcase mr-2">
        <h1>Portfolio Management</h1>
        <div className="p-card p-3 m-5">
          <div className="p-card-body">
            <form onSubmit={(e) => { e.preventDefault(); console.log('Search form values:', search); }}>
              <div className="grid">
                <div className="flex justify-content-center col-3 p-2 mt-2">
                  <div className="p-float-label w-full">
                    <InputText id="planCode" value={search.planCode} onChange={(e) => setSearch({ ...search, planCode: e.target.value })} className="w-full" />
                    <label htmlFor="planCode">Plan Code</label>
                  </div>
                </div>

                {[
                  { id: 'segment', options: ['KA','KB','KC'] },
                  { id: 'state', options: ['CA','TX','NY','FL'] },
                  { id: 'cocSeries', options: ['COC-A','COC-B','COC-C'] },
                  { id: 'license', options: ['LIC001','LIC002','LIC003'] },
                  { id: 'product', options: ['Product-A','Product-B','Product-C'] },
                  { id: 'standard', options: ['Standard','Custom'] },
                  { id: 'planType', options: ['Type-A','Type-B','Type-C'] }
                ].map(({ id, options }) => (
                  <div key={id} className="flex justify-content-center col-3 p-2 mt-2">
                    <div className="p-float-label w-full">
                      <Dropdown id={id} value={(search as any)[id]} onChange={(e) => setSearch({ ...search, [id]: e.value })} options={options.map(o => ({ label: o, value: o }))} className="w-full" placeholder=" " />
                      <label htmlFor={id}>{id === 'cocSeries' ? 'COC Series' : id.charAt(0).toUpperCase() + id.slice(1)}</label>
                    </div>
                  </div>
                ))}
              </div>
              <div className="flex">
                <Button type="button" label="Clear" size="small" outlined severity="warning" className="flex-1 flex align-items-center justify-content-center m-2" onClick={() => setSearch({ planCode:'', segment:'', state:'', cocSeries:'', license:'', product:'', standard:'', planType:'' })} />
                <Button type="submit" label="Search" size="small" outlined className="flex-1 flex align-items-center justify-content-center m-2" />
              </div>
            </form>

            <div className="p-3">
              <Table settings={tableSettings} records={tableData} loading={false} totalRecords={tableData.length} paginate enableSort pageSize={25} rowsPerPage={[10,25,50]} onPageChange={(e) => console.log('Page changed:', e)} />
            </div>
          </div>
        </div>
      </TabPanel>
      <TabPanel header="My Plans">
        <h1>My Plans</h1>
        <div className="p-card p-3 m-5">
          <MyPlans />
        </div>
      </TabPanel>
    </TabView>
  );
}

function MyPlans() {
  return <div>My Plans component is available as a dedicated route too.</div>;
}
